'use server';

import { db } from "@/lib/firebase";
import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import type { Order } from "@/lib/types";

// This type omits fields that will be generated by the server or are not part of the initial creation data.
type OrderCreationData = Omit<Order, 'id' | 'createdAt' | 'status'>;

export async function createOrder(orderData: OrderCreationData): Promise<string> {
  try {
    const orderWithTimestamp = {
      ...orderData,
      status: 'Pending', // Default status for a new order
      createdAt: serverTimestamp(),
    };
    
    const docRef = await addDoc(collection(db, "orders"), orderWithTimestamp);
    return docRef.id;
  } catch (error) {
    console.error("Error creating order: ", error);
    // Throw a more specific error to be handled by the calling function
    throw new Error("Could not create order in the database.");
  }
}
