'use client';

import { db } from "@/lib/firebase";
import { doc, serverTimestamp, runTransaction } from "firebase/firestore";
import type { Order } from "@/lib/types";

// This type omits fields that will be generated by the server or are not part of the initial creation data.
type OrderCreationData = Omit<Order, 'id' | 'createdAt' | 'status'>;

export async function createOrder(orderData: OrderCreationData): Promise<string> {
  try {
    const newOrderId = await runTransaction(db, async (transaction) => {
      const counterRef = doc(db, "counters", "orders");
      const counterDoc = await transaction.get(counterRef);

      let newOrderNumber = 1;
      if (counterDoc.exists()) {
        newOrderNumber = counterDoc.data().currentNumber + 1;
      }

      const displayId = `DG${String(newOrderNumber).padStart(6, '0')}`;

      // Update the counter document
      transaction.set(counterRef, { currentNumber: newOrderNumber }, { merge: true });

      // Create the new order document with the custom ID
      const newOrderRef = doc(db, "orders", displayId);
      const orderWithTimestamp = {
        ...orderData,
        status: 'Pending', // Default status for a new order
        createdAt: serverTimestamp(),
      };
      transaction.set(newOrderRef, orderWithTimestamp);
      
      return displayId;
    });

    return newOrderId;
  } catch (error: any) {
    console.error("Error creating order: ", error);
    // Throw a more specific error to be handled by the calling function
    const detailedMessage = `Database error: ${error.code} - ${error.message || 'Please check Firestore rules and data structure.'}`;
    throw new Error(detailedMessage);
  }
}
